host: https://e2-demo-field-eng.cloud.databricks.com/
catalog: yen_training
schema: agents
llm_endpoint: databricks-meta-llama-3-3-70b-instruct
genie_space_id: 01f0ca478c1517b2ac6fdcc04eec967f
genie_table: yen_training.agents.cust_service_data
uc_functions:
  - yen_training.agents.extract_product
  - yen_training.agents.get_requests_history
  - yen_training.agents.get_return_policy
retriever:
  tool_name: search_product_docs
  vs_endpoint: one-env-shared-endpoint-0
  vs_index: yen_training.agents.product_docs_vs
  vs_source: yen_training.agents.product_docs
  k: 5
# for agentic memory
lakebase:
  instance_name: fe-shared-demo
  database: yen_lakebase